sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
script:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -n 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  - cd acceptance-tests && ./runTests.sh && cd -
